### ISSUE TITLE
Out of the box support for JSR 310 formats

### ISSUE THREAD

**Issue by acanby** [grails-plugins/grails-java8#10]
Hi All - I alluded to this on #7, and it looks like https://github.com/grails-plugins/grails-java8/pull/6 is sort of heading in the same direction.

What I'd like to propose for discussion is that this plugin supports a superset of the default formats defined in https://github.com/grails/grails-core/blob/master/grails-plugin-databinding/src/main/groovy/org/grails/plugins/databinding/DataBindingGrailsPlugin.groovy#L47.

My current workflow is:
1. New Grails App
2. Add grails-java8 plugin
3. Set additional formats for data binding `LocalDate` and friends in application.yml

It seems like step 3 should be superfluous, given you need to explicitly add the grails-java8 plugin.

Looking at the code, I feel that this could be accomplished by using a Java 8 only list of format strings. 

Changing https://github.com/grails-plugins/grails-java8/blob/master/src/main/groovy/org/grails/plugins/web/Java8GrailsPlugin.groovy to instead 'default' to a new const `Java8GrailsPlugin.DEFAULT_JSR310_FORMATS` (values TBA) seems like an isolated change. 

I'll add in here I'm happy to submit a PR for the change, I just wanted to start a discussion with those who know more about the possible impact of the change.

**Comment by jameskleeh** [comment]
@acanby Seems fine to me as long as:

1. The list is only configured if the user has not configured any formats
2. The list contains the current default formats
3. The list contains a sensible default for each of the supported date types
