### ISSUE TITLE
Document how to change formats globally!

### ISSUE THREAD

**Issue by aadrian** [grails-plugins/grails-java8#13]
Hi,

Please document (or link if it's documented) how to change the default formats https://github.com/grails-plugins/grails-java8/blob/master/src/main/groovy/org/grails/plugins/web/Java8GrailsPlugin.groovy  globally for the entire application.

Also please provide some usage examples, as there seems to be zero docs for now (or at least they're not linked from the main pages) :( .

Thank you.

**Comment by jameskleeh** [comment]
@aadrian There isn't documentation because there really isn't anything to document. Just add the plugin and start using Java 8 date classes. The date formats for data binding uses the same configuration key as normal data binding (`grails.databinding.dateFormats`)

**Comment by aadrian** [comment]
> There isn't documentation because there really isn't anything to document. 

Maybe:

> Just add the plugin and start using Java 8 date classes. 

This sentence :) .

Also a small example in the Readme.md :).

> The date formats for data binding uses the same configuration key as normal data binding (grails.databinding.dateFormats)

So this sentence too? :) 

And also the link the the default binding http://docs.grails.org/latest/guide/single.html#dataBinding ( sub-sub-chapter "Date Formats For Data Binding" doesn't seem to have a number and an anchor to link to).

**Comment by jameskleeh** [comment]
@aadrian Feel free to create a PR for the README

**Comment by aadrian** [comment]
@jameskleeh the name is also confusing (`grails-java8`) since it has support for the new Java 8 Time API **only**, not for the other Java8 new features. Or are those planned too (lambda, stream, optional, etc.) ?

**Comment by jameskleeh** [comment]
@aadrian No additional support is necessary to use streams or optionals. Grails has no control over the lambda support since that is a Groovy language issue.
